// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnnxObjectDetectionWeb.Models;

namespace OnnxObjectDetectionWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SharedClass.DetectionBox", b =>
                {
                    b.Property<int>("DetectionBoxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("DetectionBoxId");

                    b.ToTable("DetectionBoxes");
                });

            modelBuilder.Entity("SharedClass.UserImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.ToTable("UserImages");

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            ImageName = "image1",
                            ImagePath = "imagesList/image1.jpg"
                        },
                        new
                        {
                            ImageId = 2,
                            ImageName = "image2",
                            ImagePath = "imagesList/image2.jpg"
                        },
                        new
                        {
                            ImageId = 3,
                            ImageName = "image3",
                            ImagePath = "imagesList/image3.jpg"
                        },
                        new
                        {
                            ImageId = 4,
                            ImageName = "image4",
                            ImagePath = "imagesList/image4.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
